#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xsel
Version  : 1.2.0
Release  : 1
URL      : https://github.com/kfish/xsel/archive/1.2.0.tar.gz
Source0  : https://github.com/kfish/xsel/archive/1.2.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT-Opengroup
Requires: xsel-bin = %{version}-%{release}
Requires: xsel-license = %{version}-%{release}
Requires: xsel-man = %{version}-%{release}
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xt)

%description
XSel -- manipulate the X selection.
For updates see http://www.vergenet.net/~conrad/software/xsel/

%package bin
Summary: bin components for the xsel package.
Group: Binaries
Requires: xsel-license = %{version}-%{release}

%description bin
bin components for the xsel package.


%package license
Summary: license components for the xsel package.
Group: Default

%description license
license components for the xsel package.


%package man
Summary: man components for the xsel package.
Group: Default

%description man
man components for the xsel package.


%prep
%setup -q -n xsel-1.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1553100971
export LDFLAGS="${LDFLAGS} -fno-lto"
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1553100971
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xsel
cp COPYING %{buildroot}/usr/share/package-licenses/xsel/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xsel

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xsel/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/xsel.1x
